# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aidw < Formula
  desc "Portable Claude + GitHub Copilot workflow kit for VS Code workspaces"
  homepage "https://github.com/sebGilR/ai-dev-workflow"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sebGilR/ai-dev-workflow/releases/download/v0.2.3/ai-dev-workflow_0.2.3_Darwin_x86_64.tar.gz"
      sha256 "c7f6665012501a78e297efa2a5784d87da939e2b4e2ce527f309696c55c55e2d"

      define_method(:install) do
        bin.install "aidw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sebGilR/ai-dev-workflow/releases/download/v0.2.3/ai-dev-workflow_0.2.3_Darwin_arm64.tar.gz"
      sha256 "2ece75e96fac4002a316c41a040859cdba466f8b1376470177cae143482a5d49"

      define_method(:install) do
        bin.install "aidw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebGilR/ai-dev-workflow/releases/download/v0.2.3/ai-dev-workflow_0.2.3_Linux_x86_64.tar.gz"
      sha256 "c84f150144e879ea179cc8ee6dfa76292b41569bda412e35b8b785fc00b874e8"
      define_method(:install) do
        bin.install "aidw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebGilR/ai-dev-workflow/releases/download/v0.2.3/ai-dev-workflow_0.2.3_Linux_arm64.tar.gz"
      sha256 "6aefb180b9d470a6f1e0f45f3069b6161e96ffbcd1a001c4045a3014c4499e9c"
      define_method(:install) do
        bin.install "aidw"
      end
    end
  end

  test do
    system "#{bin}/aidw --version"
  end
end
